name: "2021"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./2021

    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.126.0
        with:
          bundler-cache: true
          ruby-version: 3.1
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake test
